laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('quem-somos', 'EmpresaController@index')->name('empresa');
    Route::get('aparelhos-auditivos', 'AparelhosController@index')->name('aparelhos');
    Route::post('aparelhos-auditivos', 'AparelhosController@post')->name('aparelhos.post');
    Route::get('aparelhos-auditivos/estabelecimentos', 'AparelhosController@estabelecimentos')->name('aparelhos.estabelecimentos');
    Route::get('aparelhos-auditivos/telefone/{id}', 'AparelhosController@telefone')->name('aparelhos.telefone');
    Route::get('especialistas/telefone/{id}', 'AparelhosController@telefoneEspecialista')->name('especialistas.telefone');

    Route::group([
        'middleware' => ['auth.cadastro']
    ], function () {
        Route::get('aparelhos-auditivos/consulta/{n1}/{n2}/{n3}/{n4}/{n5}/{n6}/{n7}/{n8}/{n9}', 'AparelhosController@consulta')->name('aparelhos.consulta');
        Route::get('aparelhos-auditivos/detalhes/{id}/{n1}/{n2}/{n3}/{n4}/{n5}/{n6}/{n7}/{n8}/{n9}', 'AparelhosController@show')->name('aparelhos.show');
        Route::post('avaliacao/{tipo}', 'HomeController@avaliar')->name('avaliacao');
    });

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('pergunte-ao-especialista/{respostas_categoria?}', 'PergunteController@index')->name('pergunte');
    Route::post('pergunte-ao-especialista', 'PergunteController@post')->name('pergunte.post');
    Route::get('blog/{blog_categoria?}', 'BlogController@index')->name('blog');
    Route::get('blog/{blog_categoria}/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::get('blog/a/{ano}/{mes}', 'BlogController@arquivo')->name('blog.arquivo');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('ebook', 'BlogController@ebook')->name('ebook');
    Route::post('ebook', 'BlogController@ebookPost')->name('ebook.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');

    // Cadastro
    Route::get('selecao-login', 'HomeController@selecaoLogin')->name('selecaoLogin');
    Route::get('login', 'HomeController@login')->name('cadastro.login');
    Route::get('cadastro', 'HomeController@cadastro')->name('cadastro.cadastro');
    Route::post('cadastro', 'CadastroAuth\AuthController@create')->name('cadastro.cadastroPost');
    Route::post('login', 'CadastroAuth\AuthController@login')->name('cadastro.loginPost');
    Route::get('logout', 'CadastroAuth\AuthController@logout')->name('cadastro.logout');
    Route::get('esqueci-minha-senha', 'HomeController@esqueci')->name('cadastro.esqueci');
    Route::post('redefinicao-de-senha', 'CadastroAuth\PasswordController@sendResetLinkEmail')->name('cadastro.redefinicao');
    Route::get('redefinicao-de-senha/{token}', 'CadastroAuth\PasswordController@showResetForm');
    Route::post('redefinir-senha', 'CadastroAuth\PasswordController@reset')->name('cadastro.redefinir');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('aulas/categorias', 'AulasCategoriasController', ['parameters' => ['categorias' => 'categorias_aulas']]);
        Route::resource('aulas', 'AulasController');
        Route::resource('aulas.downloads', 'AulasDownloadsController', ['parameters' => ['downloads' => 'downloads_aulas']]);
        Route::resource('avisos', 'AvisosController');
        Route::resource('cabecalho', 'CabecalhoController', ['only' => ['index', 'update']]);
        Route::resource('aparelhos-texto', 'AparelhosTextoController', ['only' => ['index', 'update']]);
        Route::get('ebook/delete', 'EbookController@delete')->name('painel.ebook.delete');
        Route::resource('ebook', 'EbookController', ['only' => ['index', 'update']]);
        Route::get('downloads/exportar', ['as' => 'painel.downloads.exportar', 'uses' => 'DownloadsController@exportar']);
        Route::resource('downloads', 'DownloadsController');
        Route::get('consultas/exportar', ['as' => 'painel.consultas.exportar', 'uses' => 'ConsultasController@exportar']);
        Route::resource('consultas', 'ConsultasController');
        Route::get('estabelecimentos/{estabelecimentos}/aprovar', 'EstabelecimentosController@aprovar')->name('painel.estabelecimentos.aprovar');
        Route::get('estabelecimentos/exibicoes', 'EstabelecimentosController@exibicoes')->name('painel.estabelecimentos.exibicoes');
        Route::resource('estabelecimentos', 'EstabelecimentosController', [
            'except' => ['create', 'store']
        ]);
        Route::resource('aparelhos/marcas', 'AparelhosMarcasController');
        Route::resource('aparelhos/modelos', 'AparelhosModelosController');
        Route::resource('aparelhos', 'AparelhosController');
        Route::resource('resposta-em-destaque', 'RespostaEmDestaqueController', ['only' => ['index', 'update']]);
        Route::resource('respostas/categorias', 'RespostasCategoriasController', ['parameters' => ['categorias' => 'categorias_respostas']]);
        Route::resource('respostas', 'RespostasController');
        Route::get('respostas/{respostas}/avaliar', 'RespostasController@avaliar')->name('painel.respostas.avaliar');
        Route::get('respostas/{respostas}/rejeitar', 'RespostasController@rejeitar')->name('painel.respostas.rejeitar');
        Route::get('especialistas/exibicoes', 'EspecialistasController@exibicoes')->name('painel.especialistas.exibicoes');
        Route::resource('especialistas', 'EspecialistasController', ['only' => ['index', 'show', 'destroy']]);
        Route::get('especialistas/{especialistas}/aprovar', 'EspecialistasController@aprovar')->name('painel.especialistas.aprovar');
        Route::get('perguntas-recebidas/{perguntas_recebidas}/toggle', ['as' => 'painel.perguntas-recebidas.toggle', 'uses' => 'PerguntasRecebidasController@toggle']);
        Route::resource('perguntas-recebidas', 'PerguntasRecebidasController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
        Route::resource('chamadas-home', 'ChamadasHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('faq', 'FaqController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::get('cadastros/exportar', ['as' => 'painel.cadastros.exportar', 'uses' => 'CadastrosController@exportar']);
        Route::resource('cadastros', 'CadastrosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth Painel
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Especialista/PainelController.php
<?php

namespace App\Http\Controllers\Especialista;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Resposta;
use App\Models\Aviso;
use App\Models\AulaCategoria;
use App\Models\Aula;
use App\Models\Especialista;
use App\Http\Requests\EspecialistasRequest;
use App\Models\AparelhoMarca;

class PainelController extends Controller
{
    public function index()
    {
        $registro = \Auth::guard('especialista')->user();
        $marcas = AparelhoMarca::ordenados()->get();

        return view('especialista.meus-dados', compact('registro', 'marcas'));
    }

    public function update(EspecialistasRequest $request)
    {
        $registro = \Auth::guard('especialista')->user();

        $input = array_filter($request->all(), 'strlen');

        if ($input['endereco'] != $registro->endereco || $input['numero'] != $registro->numero || $input['bairro'] != $registro->bairro || $input['cidade'] != $registro->cidade || $input['uf'] != $registro->uf) {
            try {
                $endereco = "${input['endereco']} ${input['numero']} - ${input['bairro']}, ${input['cidade']} - ${input['uf']}";
                $coordenadas = \Tools::fetchCoordinates($endereco);
                $input['lat'] = $coordenadas->lat;
                $input['lng'] = $coordenadas->lng;
            } catch (\Exception $e) {
                return back()->with('erroCoord', $e->getMessage());
            }
        }

        if (isset($input['senha'])) {
            $input['senha'] = bcrypt($input['senha']);
        }

        if (isset($input['imagem'])) {
            $input['imagem'] = Especialista::upload_imagem();
        }

        $registro->update($input);

        return redirect()->back()->with('success', 'Dados atualizados com sucesso.');
    }

    public function avisos()
    {
        $avisos = Aviso::ordenados()->get();

        return view('especialista.avisos', compact('avisos'));
    }

    public function aulas(AulaCategoria $categoria)
    {
        $categorias = AulaCategoria::ordenados()->get();

        if (!$categoria->exists) {
            $categoria = AulaCategoria::ordenados()->first();
        }

        if (! $categoria) {
            if (auth('estabelecimento')->check()) {
                return redirect()->route('estabelecimento');
            }
            return redirect()->route('especialista');
        }

        $aulas = $categoria->aulas;

        return view('especialista.aulas.index', compact('categorias', 'categoria', 'aulas'));
    }

    public function aula(AulaCategoria $categoria, Aula $aula)
    {
        $categorias = AulaCategoria::ordenados()->get();

        return view('especialista.aulas.show', compact('categorias', 'aula'));
    }

    public function perguntas()
    {
        $perguntas = Resposta::where('aprovado', 0)
            ->where('especialista', null)
            ->orderBy('id', 'DESC')
            ->paginate(10);

        return view('especialista.perguntas.index', compact('perguntas'));
    }

    public function form($id)
    {
        $pergunta = Resposta::findOrFail($id);

        if ($pergunta->especialista != null) {
            abort('404');
        }

        return view('especialista.perguntas.form', compact('pergunta'));
    }

    public function post($id, Request $request)
    {
        $pergunta = Resposta::findOrFail($id);

        if ($pergunta->especialista != null) {
            abort('404');
        }

        $this->validate($request, [
            'resposta' => 'required',
        ]);

        try {
            $pergunta->update([
                'especialista' => \Auth::guard('especialista')->user()->id,
                'resposta'     => $request->get('resposta')
            ]);

            return redirect()->route('especialista.perguntas')->with('success', 'Resposta enviada com sucesso. Aguarde a validação do administrador.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);
        }
    }

    public function minhasRespostas()
    {
        $respostas = Resposta::where('aprovado', 1)
            ->where('especialista', \Auth::guard('especialista')->user()->id)
            ->orderBy('id', 'DESC')
            ->get();

        return view('especialista.perguntas.minhas-respostas', compact('respostas'));
    }
}

laravel/app/Http/Controllers/Estabelecimento/PainelController.php
<?php

namespace App\Http\Controllers\Estabelecimento;

use Illuminate\Http\Request;
use App\Http\Requests\EstabelecimentosPublicRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Aviso;
use App\Models\AulaCategoria;
use App\Models\Aula;
use App\Models\Especialista;
use App\Models\AparelhoMarca;

class PainelController extends Controller
{
    public function index()
    {
        $registro = \Auth::guard('estabelecimento')->user();
        $marcas = AparelhoMarca::ordenados()->get();

        return view('estabelecimento.meus-dados', compact('registro', 'marcas'));
    }

    public function update(EstabelecimentosPublicRequest $request)
    {
        $registro = \Auth::guard('estabelecimento')->user();

        $input = array_filter($request->except('marcas'), 'strlen');

        if ($input['endereco'] != $registro->endereco || $input['numero'] != $registro->numero || $input['bairro'] != $registro->bairro || $input['cidade'] != $registro->cidade || $input['uf'] != $registro->uf) {
            try {
                $endereco = "${input['endereco']} ${input['numero']} - ${input['bairro']}, ${input['cidade']} - ${input['uf']}";
                $coordenadas = \Tools::fetchCoordinates($endereco);
                $input['lat'] = $coordenadas->lat;
                $input['lng'] = $coordenadas->lng;
            } catch (\Exception $e) {
                return back()->with('erroCoord', $e->getMessage());
            }
        }

        if (isset($input['senha'])) {
            $input['senha'] = bcrypt($input['senha']);
        }

        $registro->update($input);
        $registro->marcas()->sync(request('marcas') ?: []);

        return redirect()->back()->with('success', 'Dados atualizados com sucesso.');
    }
}

laravel/app/Http/Controllers/Painel/AparelhosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AparelhosRequest;
use App\Http\Controllers\Controller;

use App\Models\Aparelho;
use App\Models\AparelhoMarca;
use App\Models\AparelhoModelo;

class AparelhosController extends Controller
{
    public function __construct()
    {
        view()->share([
            'marcas'  => AparelhoMarca::ordenados()->lists('titulo', 'id'),
            'modelos' => AparelhoModelo::ordenados()->lists('titulo', 'id')
        ]);
    }

    public function index()
    {
        $registros = Aparelho::ordenados()->paginate(30);

        return view('painel.aparelhos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.aparelhos.create');
    }

    public function store(AparelhosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aparelho::upload_imagem();
            if (isset($input['ampliacao'])) $input['ampliacao'] = Aparelho::upload_ampliacao();

            Aparelho::create($input);

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Aparelho $registro)
    {
        return view('painel.aparelhos.edit', compact('registro'));
    }

    public function update(AparelhosRequest $request, Aparelho $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aparelho::upload_imagem();
            if (isset($input['ampliacao'])) $input['ampliacao'] = Aparelho::upload_ampliacao();

            $registro->update($input);

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Aparelho $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/especialistas/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Especialistas /</small> Adicionar Especialista</h2>
    </legend>

    {!! Form::open(['route' => 'painel.especialistas.store', 'files' => true]) !!}

        @include('painel.especialistas.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/especialistas/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Especialistas /</small> Editar Especialista</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.especialistas.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.especialistas.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/especialistas/exibicoes.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.especialistas.index') }}" class="btn btn-default btn-sm">
        &larr; Voltar para Especialistas
    </a>

    <legend>
        <h2><small>Especialistas / </small> Exibições</h2>
    </legend>


    @if(!count($especialistas))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Exibições</th>
            </tr>
        </thead>

        <tbody>
        @foreach ($especialistas as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>{{ $registro->nome }}</td>
                <td>{{ $registro->exibicoes }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection

laravel/resources/views/painel/especialistas/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('email', 'E-mail') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('descricao', 'Descrição') !!}
    {!! Form::text('descricao', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/especialistas/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('senha', 'Senha') !!}
    {!! Form::password('senha', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('senha_confirmation', 'Confirmação de Senha') !!}
    {!! Form::password('senha_confirmation', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.especialistas.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/especialistas/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Especialistas
            <div class="btn-group pull-right">
                <a href="{{ route('painel.especialistas.exibicoes') }}" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-star" style="margin-right:10px;"></span>Exibições</a>
            </div>
        </h2>
    </legend>

    <div class="btn-group">
        <a href="{{ route('painel.especialistas.index') }}" class="btn btn-default  @if(!Request::get('aprovacao')) active @endif">Aprovados</a>
        <a href="{{ route('painel.especialistas.index', ['aprovacao' => 1]) }}" class="btn btn-default @if(Request::get('aprovacao')) active @endif">
            Aguardando aprovação
            @if($countAprovacao >= 1)
            <span class="label label-info" style="margin-left:5px;">
                {{ $countAprovacao }}
            </span>
            @endif
        </a>
    </div>

    <hr>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="especialistas">
        <thead>
            <tr>
                @if(!Request::get('aprovacao'))
                <th>Ordenar</th>
                @endif
                <th>Nome</th>
                @if(!Request::get('aprovacao'))
                <th style="text-align: center">Avaliação</th>
                @endif
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
        <tr class="tr-row" id="{{ $registro->id }}">
                @if(!Request::get('aprovacao'))
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                @endif
                <td>{{ $registro->nome }}</td>
                @if(!Request::get('aprovacao'))
                <td style="text-align: center">
                    {{ $registro->avaliacao_clientes }}<br>
                    <small>({{ $registro->avaliacoes->count() }} {{ $registro->avaliacoes->count() == 1 ? 'avaliação' : 'avaliações' }})</small>
                </td>
                @endif
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.especialistas.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.especialistas.show', $registro->id) }}" class="btn btn-info btn-sm pull-left">
                            <span class="glyphicon glyphicon-user" style="margin-right:10px;"></span>Ver dados
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection

laravel/resources/views/painel/especialistas/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Especialistas /</small> Dados do Especialista</h2>
    </legend>

    <div class="form-group">
        <label>Nome Completo</label>
        <div class="well">{{ $registro->nome }}</div>
    </div>
    <div class="form-group">
        <label>E-mail</label>
        <div class="well">{{ $registro->email }}</div>
    </div>
    <div class="form-group">
        <label>CPF</label>
        <div class="well">{{ $registro->cpf }}</div>
    </div>
    <div class="form-group">
        <label>Profissão/Cargo</label>
        <div class="well">{{ $registro->profissao_cargo }}</div>
    </div>
    <div class="form-group">
        <label>Telefone</label>
        <div class="well">{{ $registro->telefone }}</div>
    </div>
    <div class="form-group">
        <label>CEP</label>
        <div class="well">{{ $registro->cep }}</div>
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <div class="well">{{ $registro->endereco }}</div>
    </div>
    <div class="form-group">
        <label>Número</label>
        <div class="well">{{ $registro->numero }}</div>
    </div>
    @if($registro->complemento)
    <div class="form-group">
        <label>Complemento</label>
        <div class="well">{{ $registro->complemento }}</div>
    </div>
    @endif
    <div class="form-group">
        <label>Bairro</label>
        <div class="well">{{ $registro->bairro }}</div>
    </div>
    <div class="form-group">
        <label>Cidade</label>
        <div class="well">{{ $registro->cidade }}</div>
    </div>
    <div class="form-group">
        <label>UF</label>
        <div class="well">{{ $registro->uf }}</div>
    </div>
    <div class="form-group">
        <label>Nome para exibição</label>
        <div class="well">{{ $registro->nome_exibicao }}</div>
    </div>
    <div class="form-group">
        <label>Descrição</label>
        <div class="well">{{ $registro->descricao }}</div>
    </div>
    <div class="form-group">
        <label>Foto</label>
        <div class="well">
            @if($registro->imagem)
            <img src="{{ asset('assets/img/especialistas/'.$registro->imagem) }}" alt="">
            @else
            <img src="{{ asset('assets/img/layout/especialista.png') }}" alt="">
            @endif
        </div>
    </div>

    @if($registro->aprovado)
        <a href="{{ route('painel.especialistas.index') }}" class="btn btn-default btn-voltar">Voltar</a>
    @else
        <a href="{{ route('painel.especialistas.aprovar', $registro->id) }}" class="btn btn-success">
            <span class="glyphicon glyphicon-ok" style="margin-right:10px;"></span>
            Aprovar
        </a>
        <a href="{{ route('painel.especialistas.index', ['aprovacao' => 1]) }}" class="btn btn-default btn-voltar">Voltar</a>
    @endif

@stop