laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('quem-somos', 'EmpresaController@index')->name('empresa');
    Route::get('aparelhos-auditivos', 'AparelhosController@index')->name('aparelhos');
    Route::post('aparelhos-auditivos', 'AparelhosController@post')->name('aparelhos.post');
    Route::get('aparelhos-auditivos/estabelecimentos', 'AparelhosController@estabelecimentos')->name('aparelhos.estabelecimentos');
    Route::get('aparelhos-auditivos/telefone/{id}', 'AparelhosController@telefone')->name('aparelhos.telefone');
    Route::get('especialistas/telefone/{id}', 'AparelhosController@telefoneEspecialista')->name('especialistas.telefone');

    Route::group([
        'middleware' => ['auth.cadastro']
    ], function () {
        Route::get('aparelhos-auditivos/consulta/{n1}/{n2}/{n3}/{n4}/{n5}/{n6}/{n7}/{n8}/{n9}', 'AparelhosController@consulta')->name('aparelhos.consulta');
        Route::get('aparelhos-auditivos/detalhes/{id}/{n1}/{n2}/{n3}/{n4}/{n5}/{n6}/{n7}/{n8}/{n9}', 'AparelhosController@show')->name('aparelhos.show');
        Route::post('avaliacao/{tipo}', 'HomeController@avaliar')->name('avaliacao');
    });

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('pergunte-ao-especialista/{respostas_categoria?}', 'PergunteController@index')->name('pergunte');
    Route::post('pergunte-ao-especialista', 'PergunteController@post')->name('pergunte.post');
    Route::get('blog/{blog_categoria?}', 'BlogController@index')->name('blog');
    Route::get('blog/{blog_categoria}/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::get('blog/a/{ano}/{mes}', 'BlogController@arquivo')->name('blog.arquivo');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('ebook', 'BlogController@ebook')->name('ebook');
    Route::post('ebook', 'BlogController@ebookPost')->name('ebook.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');

    // Cadastro
    Route::get('selecao-login', 'HomeController@selecaoLogin')->name('selecaoLogin');
    Route::get('login', 'HomeController@login')->name('cadastro.login');
    Route::get('cadastro', 'HomeController@cadastro')->name('cadastro.cadastro');
    Route::post('cadastro', 'CadastroAuth\AuthController@create')->name('cadastro.cadastroPost');
    Route::post('login', 'CadastroAuth\AuthController@login')->name('cadastro.loginPost');
    Route::get('logout', 'CadastroAuth\AuthController@logout')->name('cadastro.logout');
    Route::get('esqueci-minha-senha', 'HomeController@esqueci')->name('cadastro.esqueci');
    Route::post('redefinicao-de-senha', 'CadastroAuth\PasswordController@sendResetLinkEmail')->name('cadastro.redefinicao');
    Route::get('redefinicao-de-senha/{token}', 'CadastroAuth\PasswordController@showResetForm');
    Route::post('redefinir-senha', 'CadastroAuth\PasswordController@reset')->name('cadastro.redefinir');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('aulas/categorias', 'AulasCategoriasController', ['parameters' => ['categorias' => 'categorias_aulas']]);
        Route::resource('aulas', 'AulasController');
        Route::resource('aulas.downloads', 'AulasDownloadsController', ['parameters' => ['downloads' => 'downloads_aulas']]);
        Route::resource('avisos', 'AvisosController');
        Route::resource('cabecalho', 'CabecalhoController', ['only' => ['index', 'update']]);
        Route::resource('aparelhos-texto', 'AparelhosTextoController', ['only' => ['index', 'update']]);
        Route::get('ebook/delete', 'EbookController@delete')->name('painel.ebook.delete');
        Route::resource('ebook', 'EbookController', ['only' => ['index', 'update']]);
        Route::get('downloads/exportar', ['as' => 'painel.downloads.exportar', 'uses' => 'DownloadsController@exportar']);
        Route::resource('downloads', 'DownloadsController');
        Route::get('consultas/exportar', ['as' => 'painel.consultas.exportar', 'uses' => 'ConsultasController@exportar']);
        Route::resource('consultas', 'ConsultasController');
        Route::get('estabelecimentos/{estabelecimentos}/aprovar', 'EstabelecimentosController@aprovar')->name('painel.estabelecimentos.aprovar');
        Route::get('estabelecimentos/exibicoes', 'EstabelecimentosController@exibicoes')->name('painel.estabelecimentos.exibicoes');
        Route::resource('estabelecimentos', 'EstabelecimentosController', [
            'except' => ['create', 'store']
        ]);
        Route::resource('aparelhos/marcas', 'AparelhosMarcasController');
        Route::resource('aparelhos/modelos', 'AparelhosModelosController');
        Route::resource('aparelhos', 'AparelhosController');
        Route::resource('resposta-em-destaque', 'RespostaEmDestaqueController', ['only' => ['index', 'update']]);
        Route::resource('respostas/categorias', 'RespostasCategoriasController', ['parameters' => ['categorias' => 'categorias_respostas']]);
        Route::resource('respostas', 'RespostasController');
        Route::get('respostas/{respostas}/avaliar', 'RespostasController@avaliar')->name('painel.respostas.avaliar');
        Route::get('respostas/{respostas}/rejeitar', 'RespostasController@rejeitar')->name('painel.respostas.rejeitar');
        Route::get('especialistas/exibicoes', 'EspecialistasController@exibicoes')->name('painel.especialistas.exibicoes');
        Route::resource('especialistas', 'EspecialistasController', ['only' => ['index', 'show', 'destroy']]);
        Route::get('especialistas/{especialistas}/aprovar', 'EspecialistasController@aprovar')->name('painel.especialistas.aprovar');
        Route::get('perguntas-recebidas/{perguntas_recebidas}/toggle', ['as' => 'painel.perguntas-recebidas.toggle', 'uses' => 'PerguntasRecebidasController@toggle']);
        Route::resource('perguntas-recebidas', 'PerguntasRecebidasController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
        Route::resource('chamadas-home', 'ChamadasHomeController', ['only' => ['index', 'update']]);
        Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('faq', 'FaqController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::get('cadastros/exportar', ['as' => 'painel.cadastros.exportar', 'uses' => 'CadastrosController@exportar']);
        Route::resource('cadastros', 'CadastrosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth Painel
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Especialista/PainelController.php
<?php

namespace App\Http\Controllers\Especialista;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Resposta;
use App\Models\Aviso;
use App\Models\AulaCategoria;
use App\Models\Aula;
use App\Models\Especialista;
use App\Http\Requests\EspecialistasRequest;
use App\Models\AparelhoMarca;

class PainelController extends Controller
{
    public function index()
    {
        $registro = \Auth::guard('especialista')->user();
        $marcas = AparelhoMarca::ordenados()->get();

        return view('especialista.meus-dados', compact('registro', 'marcas'));
    }

    public function update(EspecialistasRequest $request)
    {
        $registro = \Auth::guard('especialista')->user();

        $input = array_filter($request->all(), 'strlen');

        if ($input['endereco'] != $registro->endereco || $input['numero'] != $registro->numero || $input['bairro'] != $registro->bairro || $input['cidade'] != $registro->cidade || $input['uf'] != $registro->uf) {
            try {
                $endereco = "${input['endereco']} ${input['numero']} - ${input['bairro']}, ${input['cidade']} - ${input['uf']}";
                $coordenadas = \Tools::fetchCoordinates($endereco);
                $input['lat'] = $coordenadas->lat;
                $input['lng'] = $coordenadas->lng;
            } catch (\Exception $e) {
                return back()->with('erroCoord', $e->getMessage());
            }
        }

        if (isset($input['senha'])) {
            $input['senha'] = bcrypt($input['senha']);
        }

        if (isset($input['imagem'])) {
            $input['imagem'] = Especialista::upload_imagem();
        }

        $registro->update($input);

        return redirect()->back()->with('success', 'Dados atualizados com sucesso.');
    }

    public function avisos()
    {
        $avisos = Aviso::ordenados()->get();

        return view('especialista.avisos', compact('avisos'));
    }

    public function aulas(AulaCategoria $categoria)
    {
        $categorias = AulaCategoria::ordenados()->get();

        if (!$categoria->exists) {
            $categoria = AulaCategoria::ordenados()->first();
        }

        if (! $categoria) {
            if (auth('estabelecimento')->check()) {
                return redirect()->route('estabelecimento');
            }
            return redirect()->route('especialista');
        }

        $aulas = $categoria->aulas;

        return view('especialista.aulas.index', compact('categorias', 'categoria', 'aulas'));
    }

    public function aula(AulaCategoria $categoria, Aula $aula)
    {
        $categorias = AulaCategoria::ordenados()->get();

        return view('especialista.aulas.show', compact('categorias', 'aula'));
    }

    public function perguntas()
    {
        $perguntas = Resposta::where('aprovado', 0)
            ->where('especialista', null)
            ->orderBy('id', 'DESC')
            ->paginate(10);

        return view('especialista.perguntas.index', compact('perguntas'));
    }

    public function form($id)
    {
        $pergunta = Resposta::findOrFail($id);

        if ($pergunta->especialista != null) {
            abort('404');
        }

        return view('especialista.perguntas.form', compact('pergunta'));
    }

    public function post($id, Request $request)
    {
        $pergunta = Resposta::findOrFail($id);

        if ($pergunta->especialista != null) {
            abort('404');
        }

        $this->validate($request, [
            'resposta' => 'required',
        ]);

        try {
            $pergunta->update([
                'especialista' => \Auth::guard('especialista')->user()->id,
                'resposta'     => $request->get('resposta')
            ]);

            return redirect()->route('especialista.perguntas')->with('success', 'Resposta enviada com sucesso. Aguarde a validação do administrador.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);
        }
    }

    public function minhasRespostas()
    {
        $respostas = Resposta::where('aprovado', 1)
            ->where('especialista', \Auth::guard('especialista')->user()->id)
            ->orderBy('id', 'DESC')
            ->get();

        return view('especialista.perguntas.minhas-respostas', compact('respostas'));
    }
}

laravel/app/Http/Controllers/Estabelecimento/PainelController.php
<?php

namespace App\Http\Controllers\Estabelecimento;

use Illuminate\Http\Request;
use App\Http\Requests\EstabelecimentosPublicRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Aviso;
use App\Models\AulaCategoria;
use App\Models\Aula;
use App\Models\Especialista;
use App\Models\AparelhoMarca;

class PainelController extends Controller
{
    public function index()
    {
        $registro = \Auth::guard('estabelecimento')->user();
        $marcas = AparelhoMarca::ordenados()->get();

        return view('estabelecimento.meus-dados', compact('registro', 'marcas'));
    }

    public function update(EstabelecimentosPublicRequest $request)
    {
        $registro = \Auth::guard('estabelecimento')->user();

        $input = array_filter($request->except('marcas'), 'strlen');

        if ($input['endereco'] != $registro->endereco || $input['numero'] != $registro->numero || $input['bairro'] != $registro->bairro || $input['cidade'] != $registro->cidade || $input['uf'] != $registro->uf) {
            try {
                $endereco = "${input['endereco']} ${input['numero']} - ${input['bairro']}, ${input['cidade']} - ${input['uf']}";
                $coordenadas = \Tools::fetchCoordinates($endereco);
                $input['lat'] = $coordenadas->lat;
                $input['lng'] = $coordenadas->lng;
            } catch (\Exception $e) {
                return back()->with('erroCoord', $e->getMessage());
            }
        }

        if (isset($input['senha'])) {
            $input['senha'] = bcrypt($input['senha']);
        }

        $registro->update($input);
        $registro->marcas()->sync(request('marcas') ?: []);

        return redirect()->back()->with('success', 'Dados atualizados com sucesso.');
    }
}

laravel/app/Http/Controllers/Painel/AparelhosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AparelhosRequest;
use App\Http\Controllers\Controller;

use App\Models\Aparelho;
use App\Models\AparelhoMarca;
use App\Models\AparelhoModelo;

class AparelhosController extends Controller
{
    public function __construct()
    {
        view()->share([
            'marcas'  => AparelhoMarca::ordenados()->lists('titulo', 'id'),
            'modelos' => AparelhoModelo::ordenados()->lists('titulo', 'id')
        ]);
    }

    public function index()
    {
        $registros = Aparelho::ordenados()->paginate(30);

        return view('painel.aparelhos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.aparelhos.create');
    }

    public function store(AparelhosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aparelho::upload_imagem();
            if (isset($input['ampliacao'])) $input['ampliacao'] = Aparelho::upload_ampliacao();

            Aparelho::create($input);

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Aparelho $registro)
    {
        return view('painel.aparelhos.edit', compact('registro'));
    }

    public function update(AparelhosRequest $request, Aparelho $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aparelho::upload_imagem();
            if (isset($input['ampliacao'])) $input['ampliacao'] = Aparelho::upload_ampliacao();

            $registro->update($input);

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Aparelho $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.aparelhos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<style>
    .navbar-nav > li > a { padding-left: 12px !important; padding-right: 12px !important; }
</style>
<ul class="nav navbar-nav">
    <li class="dropdown @if(str_is('painel.cabecalho*', Route::currentRouteName()) || str_is('painel.chamadas-home*', Route::currentRouteName()) || str_is('painel.empresa*', Route::currentRouteName()) || str_is('painel.faq*', Route::currentRouteName()) || str_is('painel.politica-de-privacidade*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Páginas
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.cabecalho*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.cabecalho.index') }}">Cabeçalho</a>
            </li>
            <li @if(str_is('painel.chamadas-home*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.chamadas-home.index') }}">Home</a>
            </li>
            <li @if(str_is('painel.empresa*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.empresa.index') }}">Empresa</a>
            </li>
            <li @if(str_is('painel.faq*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.faq.index') }}">FAQ</a>
            </li>
            <li class="divider"></li>
            <li @if(str_is('painel.politica-de-privacidade*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.politica-de-privacidade.index') }}">Política de Privacidade</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.aparelhos*', Route::currentRouteName()) || str_is('painel.consultas*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Aparelhos
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.aparelhos*', Route::currentRouteName())&& !str_is('painel.aparelhos-texto*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aparelhos.index') }}">Aparelhos</a>
            </li>
            <li @if(str_is('painel.aparelhos-texto*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aparelhos-texto.index') }}">Texto</a>
            </li>
            <li @if(str_is('painel.consultas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.consultas.index') }}">Consultas</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.estabelecimentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.estabelecimentos.index') }}">Estabelecimentos</a>
    </li>
    <li class="dropdown @if(str_is('painel.especialistas*', Route::currentRouteName()) || str_is('painel.resposta*', Route::currentRouteName()) || str_is('painel.perguntas-recebidas.*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Especialistas
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.especialistas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.especialistas.index') }}">Especialistas</a>
            </li>
            <li @if(str_is('painel.respostas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.respostas.index') }}">Respostas</a>
            </li>
            <li @if(str_is('painel.resposta-em-destaque*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.resposta-em-destaque.index') }}">Resposta em destaque</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.avisos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.avisos.index') }}">Avisos</a>
    </li>
    <li @if(str_is('painel.aulas*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.aulas.index') }}">Aulas</a>
    </li>
    <li @if(str_is('painel.blog*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.blog.index') }}">Blog</a>
    </li>
    <li class="dropdown @if(str_is('painel.ebook*', Route::currentRouteName()) || str_is('painel.downloads*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Ebook
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
        	<li @if(str_is('painel.ebook*', Route::currentRouteName())) class="active" @endif>
        		<a href="{{ route('painel.ebook.index') }}">Ebook</a>
        	</li>
            <li @if(str_is('painel.downloads*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.downloads.index') }}">Downloads</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName()) || str_is('painel.newsletter*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.contato.index', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li @if(str_is('painel.contato.recebidos.*', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li class="divider"></li>
            <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
            </li>
        </ul>
        <li @if(str_is('painel.cadastros*', Route::currentRouteName())) class="active" @endif>
            <a href="{{ route('painel.cadastros.index') }}">Cadastros</a>
        </li>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>